import tkinter as tk
from tk import *
from tk import messagebox
window=Tk()
window.geometry("1366x768")
window.title("user")
window.config(bg='PaleGreen4')
def delete1():
    window3.destroy()
def refresh():
    introwindow.destroy()
    from PIL import Image
    global introwindow1
    introwindow1=Toplevel(window)
    introwindow1.geometry('1366x768')
    def mess():
        messagebox.showinfo("Success")
    def message():
        global window3
        window3=Toplevel(window)
        window3.geometry("200x200")
        window3.title("Succesfull")
        Label(window3,text="Select Properly",fg="red").pack()
        Button(window3,text="OK",command=delete1).pack()
        window3.mainloop()
    def count():
        if (mvar.get()==1 and mvar1.get()==1 and mvar2.get()==1 and mvar3.get()==1 and mvar4.get()==1 and mvar5.get()==1 and mvar6.get()==1 and mvar7.get()==0 and mvar8.get()==0 and mvar9.get()==0):
            mess()
        else:
            message()
    mvar=IntVar()
    check1=Checkbutton(introwindow1,text='Iam not a robot',font=('Times New Roman',20,'bold'),variable=mvar,state=ACTIVE,bd=5,relief=SUNKEN).place(x=550,y=80)
    introwindow1.config(bg='palegreen4')
    can1=Canvas(introwindow1,width=100,height=100)
    filename1=PhotoImage(file="cake_PNG13091.png")
    img1=can1.create_image(10,50,image=filename1)
    can1.place(x=500,y=140)
    mvar1=IntVar()
    check2=Checkbutton(introwindow1,state=ACTIVE,variable=mvar1,text='Image1',bd=5,relief=SUNKEN).place(x=500,y=250)
    can2=Canvas(introwindow1,width=100,height=100)
    filename2=PhotoImage(file="cake_PNG13118.png")
    img2=can2.create_image(10,80,image=filename2)
    can2.place(x=620,y=140)
    mvar2=IntVar()
    check3=Checkbutton(introwindow1,state=ACTIVE,variable=mvar2,text='Image2',bd=5,relief=SUNKEN).place(x=620,y=250)
    can3=Canvas(introwindow1,width=100,height=100)
    filename3=PhotoImage(file="cake_PNG13126.png")
    img1=can3.create_image(10,50,image=filename3)
    can3.place(x=740,y=140)
    mvar3=IntVar()
    check4=Checkbutton(introwindow1,state=ACTIVE,variable=mvar3,text='Image3',bd=5,relief=SUNKEN).place(x=740,y=250)
    can4=Canvas(introwindow1,width=100,height=100)
    filename4=PhotoImage(file="cake_PNG13136.png")
    img1=can4.create_image(10,50,image=filename4)
    can4.place(x=500,y=290)
    mvar4=IntVar()
    check5=Checkbutton(introwindow1,state=ACTIVE,variable=mvar4,text='Image4',bd=5,relief=SUNKEN).place(x=500,y=400)
    can5=Canvas(introwindow1,width=100,height=100)
    filename5=PhotoImage(file="cake_PNG13139.png")
    img1=can5.create_image(10,50,image=filename5)
    can5.place(x=620,y=290)
    mvar5=IntVar()
    check6=Checkbutton(introwindow1,state=ACTIVE,variable=mvar5,text='Image5',bd=5,relief=SUNKEN).place(x=620,y=400)
    can6=Canvas(introwindow1,width=100,height=100)
    filename6=PhotoImage(file="cake_PNG13140.png")
    img1=can6.create_image(10,50,image=filename6)
    can6.place(x=740,y=290)
    mvar6=IntVar()
    check7=Checkbutton(introwindow1,state=ACTIVE,variable=mvar6,text='Image6',bd=5,relief=SUNKEN).place(x=740,y=400)
    can7=Canvas(introwindow1,width=100,height=100)
    filename7=PhotoImage(file="cake_PNG13143.png")
    img1=can7.create_image(10,50,image=filename7)
    can7.place(x=500,y=440)
    mvar7=IntVar()
    check8=Checkbutton(introwindow1,state=ACTIVE,variable=mvar7,text='Image7',bd=5,relief=SUNKEN)
    check8.place(x=500,y=550)
    #check8.bg="orange"
    can8=Canvas(introwindow1,width=100,height=100)
    filename8=PhotoImage(file="C:\\Users\\hp\Pictures\\Screenshot (5).png")
    img1=can8.create_image(10,50,image=filename8)
    can8.place(x=620,y=440)
    mvar8=IntVar()
    check9=Checkbutton(introwindow1,state=ACTIVE,variable=mvar8,text='Image8',bd=5,relief=SUNKEN).place(x=620,y=550)
    
    can9=Canvas(introwindow1,width=100,height=100)
    filename9=PhotoImage(file="C:\\Users\\hp\Pictures\\Screenshot (5).png")
    img1=can9.create_image(10,50,image=filename9)
    can9.place(x=740,y=440)
    mvar9=IntVar()
    check10=Checkbutton(introwindow1,state=ACTIVE,variable=mvar9,text='Image9',bd=5,relief=SUNKEN).place(x=740,y=550)
    obj1=Button(introwindow1,text='Verify',cursor='spraycan',bg='orange',fg='white',bd=10,font=('Times New Roman',13,'bold'),width=8,relief=SUNKEN,command=count).place(x=560,y=590)
    Label(introwindow1,text='Select Images with Cakes',bd=10,font=('Times New Roman',25,'bold'),fg='bisque2',bg='orange',anchor=CENTER,relief=SUNKEN).place(x=500,y=10)
    Button(introwindow1,text="Refresh",cursor='spraycan',bg='orange',fg='bisque2',bd=10,font=('Times New Roman',13,'bold'),width=8,relief=SUNKEN,command=dest).place(x=680,y=590)
    introwindow1.mainloop()
def dest():
    introwindow1.destroy()
    success()
def delete():
    window2.destroy()  
def success():
    from PIL import Image
    global introwindow
    introwindow=Toplevel(window)
    
    introwindow.geometry('1366x768')
    def mess():
        messagebox.showinfo("Success")
    def message():
        global window2
        window2=Toplevel(window)
        window2.geometry("200x200")
        window2.title("Succesfull")
        Label(window2,text="Select Properly",fg="red").pack()
        Button(window2,text="OK",command=delete).pack()
        window2.mainloop()
    def count():
        if (mvar.get()==1 and mvar1.get()==1 and mvar2.get()==1 and mvar3.get()==1 and mvar4.get()==1 and mvar5.get()==1 and mvar6.get()==1 and mvar7.get()==0 and mvar8.get()==0 and mvar9.get()==0):
            mess()
        else:
            message()
    mvar=IntVar()
    check1=Checkbutton(introwindow,text='Iam not a robot',font=('Times New Roman',20,'bold'),variable=mvar,state=ACTIVE,bd=5,relief=SUNKEN).place(x=550,y=80)
    introwindow.config(bg='palegreen4')
    can1=Canvas(introwindow,width=100,height=100)
    filename1=PhotoImage(file="Screenshot (21).png")
    img1=can1.create_image(10,50,image=filename1)
    can1.place(x=500,y=140)
    mvar1=IntVar()
    check2=Checkbutton(introwindow,state=ACTIVE,variable=mvar1,text='Image1',bd=5,relief=SUNKEN).place(x=500,y=250)
    can2=Canvas(introwindow,width=100,height=100)
    filename2=PhotoImage(file="Screenshot (28).png")
    img2=can2.create_image(10,80,image=filename2)
    can2.place(x=620,y=140)
    mvar2=IntVar()
    check3=Checkbutton(introwindow,state=ACTIVE,variable=mvar2,text='Image2',bd=5,relief=SUNKEN).place(x=620,y=250)
    can3=Canvas(introwindow,width=100,height=100)
    filename3=PhotoImage(file="Screenshot (29).png")
    img3=can3.create_image(10,50,image=filename3)
    can3.place(x=740,y=140)
    mvar3=IntVar()
    check4=Checkbutton(introwindow,state=ACTIVE,variable=mvar3,text='Image3',bd=5,relief=SUNKEN).place(x=740,y=250)
    can4=Canvas(introwindow,width=100,height=100)
    filename4=PhotoImage(file="Screenshot (30).png")
    img4=can4.create_image(10,50,image=filename4)
    can4.place(x=500,y=290)
    mvar4=IntVar()
    check5=Checkbutton(introwindow,state=ACTIVE,variable=mvar4,text='Image4',bd=5,relief=SUNKEN).place(x=500,y=400)
    can5=Canvas(introwindow,width=100,height=100)
    filename5=PhotoImage(file="Screenshot (31).png")
    img5=can5.create_image(10,50,image=filename5)
    can5.place(x=620,y=290)
    mvar5=IntVar()
    check6=Checkbutton(introwindow,state=ACTIVE,variable=mvar5,text='Image5',bd=5,relief=SUNKEN).place(x=620,y=400)
    can6=Canvas(introwindow,width=100,height=100)
    filename6=PhotoImage(file="Screenshot (32).png")
    img6=can6.create_image(10,50,image=filename6)
    can6.place(x=740,y=290)
    mvar6=IntVar()
    check7=Checkbutton(introwindow,state=ACTIVE,variable=mvar6,text='Image6',bd=5,relief=SUNKEN).place(x=740,y=400)
    can7=Canvas(introwindow,width=100,height=100)
    filename7=PhotoImage(file="cake_PNG13091.png")
    img7=can7.create_image(10,50,image=filename7)
    can7.place(x=500,y=440)
    mvar7=IntVar()
    check8=Checkbutton(introwindow,state=ACTIVE,variable=mvar7,text='Image7',bd=5,relief=SUNKEN)
    check8.place(x=500,y=550)
    #check8.config(bg="orange")
    can8=Canvas(introwindow,width=100,height=100)
    filename8=PhotoImage(file="cake_PNG13118.png")
    img8=can8.create_image(10,50,image=filename8)
    can8.place(x=620,y=440)
    mvar8=IntVar()
    check9=Checkbutton(introwindow,state=ACTIVE,variable=mvar8,text='Image8',bd=5,relief=SUNKEN).place(x=620,y=550)
    
    can9=Canvas(introwindow,width=100,height=100)
    filename9=PhotoImage(file="cake_PNG13126.png")
    img9=can9.create_image(10,50,image=filename9)
    can9.place(x=740,y=440)
    mvar9=IntVar()
    check10=Checkbutton(introwindow,state=ACTIVE,variable=mvar9,text='Image9',bd=5,relief=SUNKEN).place(x=740,y=550)
    obj1=Button(introwindow,text='Verify',cursor='spraycan',bg='orange',fg='white',bd=10,font=('Times New Roman',13,'bold'),width=8,relief=SUNKEN,command=count).place(x=560,y=590)
    Label(introwindow,text='Select Images with Car',bd=10,font=('Times New Roman',25,'bold'),fg='bisque2',bg='orange',anchor=CENTER,relief=SUNKEN).place(x=500,y=10)
    Button(introwindow,text="Refresh",cursor='spraycan',bg='orange',fg='bisque2',bd=10,font=('Times New Roman',13,'bold'),width=8,relief=SUNKEN,command=refresh).place(x=680,y=590)
    introwindow.mainloop()

def error():
    messagebox.showwarning('All fields required!')
def Submit():
    name_text=name.get()
    Gmail_text=Gmail.get()
    import sqlite3
    x=sqlite3.connect("xyz.db")
    print("Success")
    #x.execute("create table dataa(name stringvar,Gmail stringvar)")
    x.execute("insert into dataa values(?,?)",(name_text,Gmail_text))
    x.commit()
    x.close()
    c=sqlite3.connect("xyz.db")
    cursor=c.execute("select name,Gmail from dataa")
    for i in cursor:
        print(i)

    if name_text=="":
        error()
    elif Gmail_text=="":
        error()
    elif name_text.isdigit():
        error()
    elif Gmail_text.isdigit():
        error()
    else:
        success()
       

Label(window,text='Welcome to Image_Captcha',cursor='arrow',bd=10,font=('Times New Roman',40,'bold','underline'),fg='bisque2',bg='cadetblue',height=3,width=40,anchor=CENTER,relief=SUNKEN).place(x=35,y=10)
Label(window,text='User_Name: ',cursor='arrow',bd=10,font=('Times New Roman',20,'bold','underline'),height=2,bg='dark orange',width=15,anchor=W,relief=GROOVE).place(x=50,y=300)
Label(window,text='Gmail: ',cursor='arrow',bd=10,font=('Times New Roman',20,'bold','underline'),height=2,bg='dark orange',width=15,anchor=W,relief=GROOVE).place(x=50,y=400)
name=StringVar()
Gmail=StringVar()

e=Entry(window,textvariable=name,cursor='arrow',bd=10,fg='azure',font=('Times New Roman',15,'bold'),bg='black',width=20,relief=SUNKEN).place(x=350,y=325)
e1=Entry(window,textvariable=Gmail,cursor='arrow',fg='azure',bd=10,font=('Times New Roman',15,'bold'),bg='black',width=20,relief=SUNKEN).place(x=350,y=425)
#e.config(validate="key")
Button(window,text='Submit',cursor='watch',bg='black',fg='red',bd=10,font=('Times New Roman',20,'bold'),width=15,relief=SUNKEN,command=Submit).place(x=700,y=500)
